name       : networkmanager-openconnect
version    : 1.2.6
release    : 16
source     :
    - https://download.gnome.org/sources/NetworkManager-openconnect/1.2/NetworkManager-openconnect-1.2.6.tar.xz : 95109803596a9782680a5dca3b51c4ad8ff7e126169d5431278cab694112975a
license    : GPL-2.0-or-later
component  : network.base
summary    : OpenConnect VPN plugin for NetworkManager
description: |
    OpenConnect VPN plugin for NetworkManager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libnm)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(openconnect)
setup      : |
    # Only dbus-1 goes into sysconfdir (etc by default) so move it
    %configure --disable-static --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/nm-openconnect.sysusers $installdir/%libdir%/sysusers.d/nm-openconnect.conf
