name       : networkmanager-openconnect
version    : 1.2.4
release    : 10
source     :
    - https://download.gnome.org/sources/NetworkManager-openconnect/1.2/NetworkManager-openconnect-1.2.4.tar.xz : a177e0cf683b63e225ecc08049a1d57f05868b5660f0907c65d5ecab39474996
license    : GPL-2.0-or-later
component  : network.base
summary    : OpenConnect VPN plugin for NetworkManager
description: |
    OpenConnect VPN plugin for NetworkManager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnm)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libxml-2.0)
    - pkgconfig(openconnect)
setup      : |
    %configure --disable-static --without-libnm-glib
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/nm-openconnect.sysusers $installdir/%libdir%/sysusers.d/nm-openconnect.conf
